services:
  - type: web
    name: bug-explorer
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: bug-explorer
          property: port
    routes:
      - type: rewrite
        source: /*
        destination: /index.html